FROM docker:19.03.1-dind
MAINTAINER Arnaud Lafon <arnaud.lafon@gmail.com>

RUN apk add --no-cache --update py-pip python-dev libffi-dev openssl-dev gcc libc-dev make git
RUN pip install docker-compose
