# Alpine image with ansible and basic tools such as make and git
FROM python:3-alpine
MAINTAINER Arnaud Lafon <arnaud.lafon@gmail.com>

RUN apk add --update --no-cache \
	ansible bash openssh make rsync git
