name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  ansible-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: ansible
            subdir: debian-buster
          - image: ansible
            subdir: debian-buster-tools
          - image: ansible
            subdir: ezplatform-toolbox
    steps:
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - 
        name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:${{ matrix.image }}/${{ matrix.subdir }}"
          file: ./Dockerfile
          push: true
          tags: ghcr.io/code-rhapsodie/docker/"${{ matrix.image }}:${{ matrix.subdir }}"